<?php

namespace CupCakesBundle\Repository;

/**
 * CategorieRecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRecRepository extends \Doctrine\ORM\EntityRepository
{
}
