<?php

namespace CupCakesBundle\Repository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNote($idUser,$idRec)
    {
        $q=$this->createQueryBuilder('n')
            ->where('n.idRec=:idRec')
            ->andWhere('n.idUser=:idUser')
            ->setParameter(':idRec',$idRec)
            ->setParameter('idUser',$idUser)
        ;
        return $q->getQuery()->getOneOrNullResult();
    }

    public function avgNote($idRec)
    {
        $q=$this->createQueryBuilder('n')
            ->select('avg(n.note)')
            ->where('n.idRec=:idRec')
            ->setParameter(':idRec',$idRec);
        return $q->getQuery()->getOneOrNullResult();
    }

}
