<?php

namespace CupCakesBundle\Repository;

/**
 * recetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class recetteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNom($nom)
    {
        $q=$this->createQueryBuilder('r')
            ->where('r.nomRec LIKE :nom')
            ->setParameter(':nom','%'.$nom.'%')
        ;
        return $q->getQuery()->getResult();
    }

}
