<?php

namespace CupCakesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * tagRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class tagRepository extends EntityRepository
{
}
